# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading 

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).

### 2. Create a random tensor with shape `(7, 7)`.

In [1]:
import torch
tensor_rand = torch.rand(7,7)

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [2]:
import torch
tensor_rand_A = torch.rand(7,7)
tensor_rand_B = torch.rand(1,7)
print(torch.matmul(tensor_rand_A,tensor_rand_B.T))

tensor([[2.1603],
        [1.9645],
        [1.6453],
        [1.2805],
        [2.0138],
        [1.5912],
        [2.4935]])


### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [4]:
import torch
RANDOM_SEED = 0
torch.manual_seed(RANDOM_SEED)
tensor_rand_A = torch.rand(1,7)
torch.manual_seed(RANDOM_SEED)
tensor_rand_B = torch.rand(1,7)
print(torch.matmul(tensor_rand_A,tensor_rand_B.T))

tensor([[1.5985]])


### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [4]:
import torch
torch.cuda.is_available()
device = 'cuda' if torch.cuda.is_available() else 'cpu'
RANDOM_SEED = 1234
torch.manual_seed(RANDOM_SEED)
tensor_rand_A = torch.rand(2,3,device=device)
print(tensor_rand_A)
tensor_rand_B = torch.rand(3,2,device=device)
print(torch.matmul(tensor_rand_A,tensor_rand_B))

tensor([[0.1272, 0.8167, 0.5440],
        [0.6601, 0.2721, 0.9737]], device='cuda:0')
tensor([[0.7154, 0.2908],
        [1.1616, 0.3998]], device='cuda:0')


In [8]:
rand_tensor = torch.arange(1,10)
print(rand_tensor)
print(torch.min(tensor_rand_A))
print(torch.max(tensor_rand_A))

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor(0.1272, device='cuda:0')
tensor(0.9737, device='cuda:0')


In [9]:
print(torch.argmin(tensor_rand_A))
print(torch.argmax(tensor_rand_A))

tensor(0, device='cuda:0')
tensor(5, device='cuda:0')


In [14]:
RANDOM_SEED = 1234
torch.manual_seed(RANDOM_SEED)

rand_tensor = torch.rand(1,1,1,10)
print(rand_tensor)
print(rand_tensor.shape)
rand_dim = rand_tensor.squeeze()
print(rand_dim)
print(rand_dim.shape)

tensor([[[[0.0290, 0.4019, 0.2598, 0.3666, 0.0583, 0.7006, 0.0518, 0.4681,
           0.6738, 0.3315]]]])
torch.Size([1, 1, 1, 10])
tensor([0.0290, 0.4019, 0.2598, 0.3666, 0.0583, 0.7006, 0.0518, 0.4681, 0.6738,
        0.3315])
torch.Size([10])
