In [118]:
print("Hello")

Hello


In [119]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt 
print(torch.__version__)

2.1.0+cu121


## Introduction to tensors

#### Creating tensors

In [120]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [121]:
torch.tensor([[1.0,-1],[1.,-1.]])
torch.tensor(np.array([[1,2,3],[4,5,6]]))


tensor([[1, 2, 3],
        [4, 5, 6]])

##### tensor always copies data. Use requires_grad to change the requires_grad 
##### use detach() to avoid making copy

In [122]:
torch.zeros([2,4],dtype=torch.int32)
torch.zeros([2,4],dtype=torch.float32) 

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [123]:
cuda0 = torch.device('cuda:1')
torch.ones([2,4],dtype=torch.float16,device=cuda0)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]], device='cuda:1', dtype=torch.float16)

In [124]:
scalar = torch.tensor(7)
print(scalar.ndim)

0


In [125]:
vector = torch.tensor([7,7])
print(vector.ndim)

1


In [126]:
MATRIX = torch.tensor([[6,7],[8,9]])
print(MATRIX)
print(MATRIX.ndim)
print(MATRIX.shape)

tensor([[6, 7],
        [8, 9]])
2
torch.Size([2, 2])


In [127]:
MATRIX = torch.tensor([[[6,7,9,8],[8,9,8,9],[3,4,8,9]]])
print(MATRIX.shape)
#  3,2

torch.Size([1, 3, 4])


In [128]:
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.6009, 0.2566, 0.7936, 0.9408],
        [0.1332, 0.9346, 0.5936, 0.8694],
        [0.5677, 0.7411, 0.4294, 0.8854]])

In [129]:
random_image_size_tensor = torch.rand(3,4,5)
print(random_image_size_tensor)

tensor([[[0.5739, 0.2666, 0.6274, 0.2696, 0.4414],
         [0.2969, 0.8317, 0.1053, 0.2695, 0.3588],
         [0.1994, 0.5472, 0.0062, 0.9516, 0.0753],
         [0.8860, 0.5832, 0.3376, 0.8090, 0.5779]],

        [[0.9040, 0.5547, 0.3423, 0.6343, 0.3644],
         [0.7104, 0.9464, 0.7890, 0.2814, 0.7886],
         [0.5895, 0.7539, 0.1952, 0.0050, 0.3068],
         [0.1165, 0.9103, 0.6440, 0.7071, 0.6581]],

        [[0.4913, 0.8913, 0.1447, 0.5315, 0.1587],
         [0.6542, 0.3278, 0.6532, 0.3958, 0.9147],
         [0.2036, 0.2018, 0.2018, 0.9497, 0.6666],
         [0.9811, 0.0874, 0.0041, 0.1088, 0.1637]]])


In [130]:
random_image_size_tensor = torch.rand(size=(3,4,5))
print(random_image_size_tensor)

tensor([[[0.7025, 0.6790, 0.9155, 0.2418, 0.1591],
         [0.7653, 0.2979, 0.8035, 0.3813, 0.7860],
         [0.1115, 0.2477, 0.6524, 0.6057, 0.3725],
         [0.7980, 0.8399, 0.1374, 0.2331, 0.9578]],

        [[0.3313, 0.3227, 0.0162, 0.2137, 0.6249],
         [0.4340, 0.1371, 0.5117, 0.1585, 0.0758],
         [0.2247, 0.0624, 0.1816, 0.9998, 0.5944],
         [0.6541, 0.0337, 0.1716, 0.3336, 0.5782]],

        [[0.0600, 0.2846, 0.2007, 0.5014, 0.3139],
         [0.4654, 0.1612, 0.1568, 0.2083, 0.3289],
         [0.1054, 0.9192, 0.4008, 0.9302, 0.6558],
         [0.0766, 0.8460, 0.3624, 0.3083, 0.0850]]])


In [131]:
random_image_size_tensor = torch.rand(size=(3,200,200)) # height, width, color cannel
print(random_image_size_tensor)

tensor([[[0.0029, 0.6431, 0.3908,  ..., 0.7487, 0.1281, 0.4384],
         [0.7399, 0.2686, 0.4455,  ..., 0.8359, 0.4812, 0.0297],
         [0.5219, 0.1595, 0.9066,  ..., 0.7698, 0.9112, 0.1225],
         ...,
         [0.3745, 0.5269, 0.2215,  ..., 0.7190, 0.6817, 0.4030],
         [0.2534, 0.8078, 0.3160,  ..., 0.9397, 0.9420, 0.7088],
         [0.5670, 0.1141, 0.7658,  ..., 0.7541, 0.2575, 0.4263]],

        [[0.5229, 0.2172, 0.7042,  ..., 0.6260, 0.7569, 0.8127],
         [0.3356, 0.7617, 0.5575,  ..., 0.6409, 0.2680, 0.8416],
         [0.1022, 0.9883, 0.9247,  ..., 0.0195, 0.3554, 0.6456],
         ...,
         [0.9994, 0.0078, 0.0061,  ..., 0.6077, 0.6992, 0.6176],
         [0.4127, 0.0090, 0.6091,  ..., 0.7099, 0.9400, 0.8409],
         [0.4196, 0.1228, 0.1440,  ..., 0.3646, 0.8498, 0.3721]],

        [[0.1017, 0.2524, 0.4054,  ..., 0.1181, 0.9444, 0.1367],
         [0.5066, 0.7729, 0.0380,  ..., 0.4347, 0.8936, 0.6735],
         [0.5411, 0.1188, 0.6353,  ..., 0.8796, 0.5212, 0.

### Creating a range of tensors and tensor-like

In [132]:
one_to_ten = torch.arange(start=1,end=1000,step=50)
print(one_to_ten)
zeros_like = torch.zeros_like(input=one_to_ten)
print(zeros_like)

tensor([  1,  51, 101, 151, 201, 251, 301, 351, 401, 451, 501, 551, 601, 651,
        701, 751, 801, 851, 901, 951])
tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])


### Tensors Datatype

#### Note: Tensor datatype is one of the 3 big errors
#### 1. Tensors not right datatypes
#### 2. Tensors not right shape
#### 3. Tensors not on the right device

In [133]:
float_32_tensor = torch.tensor([1,2,4],
                               dtype=torch.float16,
                               device="cuda", 
                               requires_grad=False) # wheather or not to track tensor.

In [134]:
float_32_tensor

tensor([1., 2., 4.], device='cuda:0', dtype=torch.float16)

In [135]:
some_tensors = torch.rand(3,4)
print(f' dtype {some_tensors.dtype}')

 dtype torch.float32


## Manipulating tensors
### Tensor operation include
* Addition
* Subtraction
* Multiplication ( Element-wise)
* Division
* Matrix

In [136]:
random_tensor = torch.tensor([1,2,3])

In [137]:
print(random_tensor*10)
print(random_tensor+10)

tensor([10, 20, 30])
tensor([11, 12, 13])


In [138]:
print(random_tensor.mul(10))

tensor([10, 20, 30])


### Tensor Agregation

In [139]:
x = torch.arange(0,100,10)
print(x.min())
print(torch.min(x))

tensor(0)
tensor(0)


In [140]:
x = torch.arange(0,100,10)
print(x.max())
print(torch.max(x))


tensor(90)
tensor(90)


In [141]:
x = torch.arange(0,100,10)
print(x.sum())
print(torch.sum(x))

tensor(450)
tensor(450)


In [142]:
x = torch.arange(0,100,10)
# print(x.mean())
print(torch.mean(x.type(torch.float64)))

tensor(45., dtype=torch.float64)


### Reshaping stacking, squeezing, unsqueezing, view, permute

In [143]:
import torch
x = torch.arange(1.0,10.0)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [144]:
x_reshape = x.reshape(3,3)
x_reshape

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [145]:
x_stacked = torch.stack([x,x],dim=0)
print(x)
print(x_stacked)
print(x.shape)
print(x_stacked.shape)
x_stacked_dim1 = torch.stack([x,x],dim=1)
print(x_stacked_dim1)
print(x_stacked_dim1.shape)

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])
tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.]])
torch.Size([9])
torch.Size([2, 9])
tensor([[1., 1.],
        [2., 2.],
        [3., 3.],
        [4., 4.],
        [5., 5.],
        [6., 6.],
        [7., 7.],
        [8., 8.],
        [9., 9.]])
torch.Size([9, 2])


In [146]:
x_ran = torch.rand(2,10)
print(x_ran)
print(x_ran.shape)
x_squeeze = x_ran.squeeze()
print(x_squeeze)
print(x_squeeze.shape)
x_unsqueeze = x_ran.unsqueeze(1)
print(x_unsqueeze)
print(x_unsqueeze.shape)
print(x_unsqueeze.permute(2,0,1))

tensor([[0.5710, 0.4608, 0.8814, 0.9251, 0.2980, 0.6212, 0.1272, 0.9698, 0.7267,
         0.6431],
        [0.3466, 0.1187, 0.5686, 0.4823, 0.7226, 0.5607, 0.4672, 0.5184, 0.0486,
         0.4226]])
torch.Size([2, 10])
tensor([[0.5710, 0.4608, 0.8814, 0.9251, 0.2980, 0.6212, 0.1272, 0.9698, 0.7267,
         0.6431],
        [0.3466, 0.1187, 0.5686, 0.4823, 0.7226, 0.5607, 0.4672, 0.5184, 0.0486,
         0.4226]])
torch.Size([2, 10])
tensor([[[0.5710, 0.4608, 0.8814, 0.9251, 0.2980, 0.6212, 0.1272, 0.9698,
          0.7267, 0.6431]],

        [[0.3466, 0.1187, 0.5686, 0.4823, 0.7226, 0.5607, 0.4672, 0.5184,
          0.0486, 0.4226]]])
torch.Size([2, 1, 10])
tensor([[[0.5710],
         [0.3466]],

        [[0.4608],
         [0.1187]],

        [[0.8814],
         [0.5686]],

        [[0.9251],
         [0.4823]],

        [[0.2980],
         [0.7226]],

        [[0.6212],
         [0.5607]],

        [[0.1272],
         [0.4672]],

        [[0.9698],
         [0.5184]],

        [[0.7

### Reproduciblity
### Indexing


In [147]:
x = torch.arange(1,10).reshape(1,3,3)
print(x)

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])


In [148]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [149]:
x[0][0]

tensor([1, 2, 3])

In [150]:
x[0,0,:]

tensor([1, 2, 3])

In [151]:
import numpy as np
ndarray = np.arange(1,10)

In [152]:
tensor = torch.from_numpy(ndarray)
print(tensor)

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])


In [153]:
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(5)
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(5)

In [154]:
random_tensor_C == random_tensor_D

tensor([True, True, True, True, True])

In [155]:
import torch
torch.cuda.is_available()
device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(device)
torch.cuda.device_count()
tensor = torch.tensor([1,2,3])
tensor_on_gpu = tensor.to(device)
tensor_on_cpu = tensor_on_gpu.cpu()

cuda


In [ ]:
import torch
torch.cuda.is_available()
device = 'cuda' if torch.cuda.is_available() else 'cpu'
